import Foundation

/// 词汇专项词库。起步 20 词：10 个高频搭配辨析易混词对 + 10 个熟词僻义，三种练法(拼写/搭配/僻义)共用。
enum VocabData {

    static let all: [VocabWord] = collocationWords + polysemyWords + collocationWords2 + polysemyWords2

    static func find(_ id: String) -> VocabWord? { all.first { $0.id == id } }
    /// 按拼写(大小写不敏感)查找，供错因诊断里"具体是哪个词"的自由输入匹配。
    static func find(headword: String) -> VocabWord? {
        let target = headword.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !target.isEmpty else { return nil }
        return all.first { $0.headword.lowercased() == target }
    }

    // MARK: 搭配辨析·易混词对

    static let collocationWords: [VocabWord] = [
        VocabWord(id: "v_raise", headword: "raise", meaning: "vt. 提高；筹集；抚养(及物，必须带宾语)", tier: 1, category: .collocation,
            example: "The charity managed to raise over ten thousand yuan for the flood victims.",
            exampleMeaning: "这家慈善机构为洪灾受害者筹集了超过一万元。",
            collocations: ["raise money", "raise a question", "raise one's hand"],
            quizStem: "The charity managed to ___ over ten thousand yuan for the flood victims.",
            quizOptions: ["raise", "rise", "lift", "grow"], quizAnswer: 0,
            quizExplanation: "raise 及物，后接宾语 money；rise 不及物，不能直接接宾语。"),
        VocabWord(id: "v_rise", headword: "rise", meaning: "vi. 上升；增长(不及物，不接宾语)", tier: 1, category: .collocation,
            example: "Prices have risen sharply this year, surprising many shoppers.",
            exampleMeaning: "今年物价大幅上涨，让许多购物者感到惊讶。",
            collocations: ["prices rise", "the sun rises", "rise to the challenge"],
            quizStem: "Prices have ___ sharply this year, surprising many shoppers.",
            quizOptions: ["risen", "raised", "rose", "raise"], quizAnswer: 0,
            quizExplanation: "have+过去分词构成现在完成时，rise 的过去分词是 risen；raised 需要宾语，此处主语 prices 是自己上涨，应用不及物的 rise。"),
        VocabWord(id: "v_affect", headword: "affect", meaning: "vt. 影响(及物动词)", tier: 1, category: .collocation,
            example: "Lack of sleep can seriously affect your ability to concentrate.",
            exampleMeaning: "睡眠不足会严重影响你的注意力。",
            collocations: ["affect one's health", "affect the result"],
            quizStem: "Lack of sleep can seriously ___ your ability to concentrate.",
            quizOptions: ["affect", "effect", "effort", "afford"], quizAnswer: 0,
            quizExplanation: "affect 是动词'影响'；effect 是名词'效果'，词性不对就不能直接作谓语。"),
        VocabWord(id: "v_effect", headword: "effect", meaning: "n. 效果；影响", tier: 1, category: .collocation,
            example: "The new policy had a positive effect on local businesses.",
            exampleMeaning: "新政策对当地企业产生了积极影响。",
            collocations: ["have an effect on", "in effect", "side effect"],
            quizStem: "The new policy had a positive ___ on local businesses.",
            quizOptions: ["effect", "affect", "cause", "reason"], quizAnswer: 0,
            quizExplanation: "have a(n)...effect on 是固定搭配，effect 在此作名词；affect 是动词，不能用在 a positive ___ 这个名词位置。"),
        VocabWord(id: "v_borrow", headword: "borrow", meaning: "vt. 借(入)，向别人借", tier: 1, category: .collocation,
            example: "Could I borrow your dictionary for a moment?",
            exampleMeaning: "我能借用一下你的词典吗？",
            collocations: ["borrow sth from sb", "borrow money"],
            quizStem: "Could I ___ your dictionary for a moment?",
            quizOptions: ["borrow", "lend", "rent", "owe"], quizAnswer: 0,
            quizExplanation: "borrow(借入)的方向是'我向你借'；lend(借出)方向相反，是'你借给我'。"),
        VocabWord(id: "v_lend", headword: "lend", meaning: "vt. 借(出)，借给别人", tier: 1, category: .collocation,
            example: "Could you lend me your dictionary for a moment?",
            exampleMeaning: "你能把词典借给我用一下吗？",
            collocations: ["lend sb sth", "lend a hand"],
            quizStem: "Could you ___ me your dictionary for a moment?",
            quizOptions: ["lend", "borrow", "rent", "owe"], quizAnswer: 0,
            quizExplanation: "lend sb sth = 借给某人某物，方向是'你借给我'；borrow 方向相反，是'我向你借'。"),
        VocabWord(id: "v_except", headword: "except", meaning: "prep. 除……之外(排除)", tier: 2, category: .collocation,
            example: "Everyone attended the meeting except Tom, who was ill.",
            exampleMeaning: "除了生病的 Tom，所有人都参加了会议。",
            collocations: ["except for", "everyone except"],
            quizStem: "Everyone attended the meeting ___ Tom, who was ill.",
            quizOptions: ["except", "expect", "accept", "exact"], quizAnswer: 0,
            quizExplanation: "except 表'排除'；expect(期待)/accept(接受)/exact(精确的)都是形近词混淆。"),
        VocabWord(id: "v_expect", headword: "expect", meaning: "vt. 期待，预料", tier: 1, category: .collocation,
            example: "We expect the package to arrive by Friday.",
            exampleMeaning: "我们预计包裹周五前会到。",
            collocations: ["expect sb to do sth", "as expected"],
            quizStem: "We ___ the package to arrive by Friday.",
            quizOptions: ["expect", "except", "accept", "exact"], quizAnswer: 0,
            quizExplanation: "expect sb/sth to do = 期待/预料……会做……；except 意为'除了'，语义不通。"),
        VocabWord(id: "v_economic", headword: "economic", meaning: "adj. 经济的(指整体经济、政策层面)", tier: 2, category: .collocation,
            example: "The government announced several new economic policies to boost growth.",
            exampleMeaning: "政府宣布了几项新的经济政策以促进增长。",
            collocations: ["economic policy", "economic growth"],
            quizStem: "The government announced several new ___ policies to boost growth.",
            quizOptions: ["economic", "economical", "economy", "economics"], quizAnswer: 0,
            quizExplanation: "economic policy(经济政策)是固定搭配；economical 指'节约的'，不能修饰国家层面的政策。"),
        VocabWord(id: "v_economical", headword: "economical", meaning: "adj. 节约的，省钱的(指具体使用方式)", tier: 2, category: .collocation,
            example: "This small car is very economical to run.",
            exampleMeaning: "这辆小车开起来很省油、很省钱。",
            collocations: ["economical to run", "an economical choice"],
            quizStem: "This small car is very ___ to run, costing very little on fuel.",
            quizOptions: ["economical", "economic", "economy", "economics"], quizAnswer: 0,
            quizExplanation: "economical 指'省钱的'，修饰具体的使用方式(开车省油)；economic 指宏观经济层面，搭配对象不同。"),
    ]

    // MARK: 熟词僻义

    static let polysemyWords: [VocabWord] = [
        VocabWord(id: "v_address", headword: "address", meaning: "常义:n. 地址；僻义:vt. 解决，处理", tier: 1, category: .polysemy,
            example: "The committee promised to address the problem of overcrowded classrooms.",
            exampleMeaning: "委员会承诺解决教室拥挤的问题。",
            collocations: ["address a problem", "address an issue"],
            quizStem: "The committee promised to address the problem of overcrowded classrooms. \"Address\" here most likely means ___.",
            quizOptions: ["解决，处理", "地址", "发表演讲", "称呼"], quizAnswer: 0,
            quizExplanation: "address the problem = 解决问题，是动词的僻义；'地址'是它的常见义，此处词性(动词)和语境都不符。"),
        VocabWord(id: "v_last", headword: "last", meaning: "常义:adj. 最后的；僻义:vi. 持续", tier: 1, category: .polysemy,
            example: "The meeting lasted nearly two hours, much longer than expected.",
            exampleMeaning: "会议持续了将近两个小时，比预期长得多。",
            collocations: ["last for hours", "a lasting impression"],
            quizStem: "The meeting lasted nearly two hours, much longer than expected. \"Lasted\" here means ___.",
            quizOptions: ["持续", "排在最后", "勉强够用", "仅仅"], quizAnswer: 0,
            quizExplanation: "lasted nearly two hours = 持续了将近两小时，是动词僻义；'最后的'是形容词常见义，与本句词性不符。"),
        VocabWord(id: "v_figure", headword: "figure", meaning: "常义:n. 数字；僻义:n. 人物；figure out 想出", tier: 1, category: .polysemy,
            example: "She is regarded as a key figure in the fight against climate change.",
            exampleMeaning: "她被视为应对气候变化斗争中的关键人物。",
            collocations: ["a key figure", "figure out"],
            quizStem: "She is regarded as a key figure in the fight against climate change. \"Figure\" here means ___.",
            quizOptions: ["人物", "数字", "图形", "身材"], quizAnswer: 0,
            quizExplanation: "a key figure = 关键人物，是名词僻义；'数字'是常见义，与 key(关键的)搭配不符。"),
        VocabWord(id: "v_subject", headword: "subject", meaning: "常义:n. 科目/主题；僻义:be subject to 使遭受", tier: 1, category: .polysemy,
            example: "Workers in the factory were subjected to extremely poor conditions.",
            exampleMeaning: "工厂里的工人遭受着极其恶劣的工作条件。",
            collocations: ["be subject to", "subject sb to sth"],
            quizStem: "Workers in the factory were subjected to extremely poor conditions. \"Subjected to\" here means ___.",
            quizOptions: ["使遭受", "以……为科目", "使服从", "以……为主题"], quizAnswer: 0,
            quizExplanation: "be subjected to = 遭受，是固定搭配的僻义；'科目/主题'是名词常见义，与本句的被动结构不符。"),
        VocabWord(id: "v_content", headword: "content", meaning: "常义:n. 内容；僻义:adj. be content with 满足的", tier: 2, category: .polysemy,
            example: "Although he wasn't rich, he was content with his simple life.",
            exampleMeaning: "尽管他并不富有，但他对自己简朴的生活感到满足。",
            collocations: ["be content with", "table of contents"],
            quizStem: "Although he wasn't rich, he was content with his simple life. \"Content\" here means ___.",
            quizOptions: ["满足的", "内容", "目录", "含量"], quizAnswer: 0,
            quizExplanation: "be content with = 对……感到满足，是形容词僻义；'内容'是名词常见义，词性和语境都不符。"),
        VocabWord(id: "v_novel", headword: "novel", meaning: "常义:n. 小说；僻义:adj. 新颖的", tier: 2, category: .polysemy,
            example: "Scientists proposed a novel approach to treating the disease.",
            exampleMeaning: "科学家提出了一种治疗这种疾病的新颖方法。",
            collocations: ["a novel idea", "a novel approach"],
            quizStem: "Scientists proposed a novel approach to treating the disease. \"Novel\" here means ___.",
            quizOptions: ["新颖的", "小说", "著名的", "复杂的"], quizAnswer: 0,
            quizExplanation: "a novel approach = 新颖的方法，是形容词僻义；'小说'是名词常见义，此处修饰 approach，须是形容词。"),
        VocabWord(id: "v_bear", headword: "bear", meaning: "常义:n. 熊；僻义:vt. 忍受/承担", tier: 1, category: .polysemy,
            example: "She could hardly bear the pain after the surgery.",
            exampleMeaning: "手术后她几乎无法忍受那种疼痛。",
            collocations: ["bear the pain", "bear responsibility"],
            quizStem: "She could hardly bear the pain after the surgery. \"Bear\" here means ___.",
            quizOptions: ["忍受", "熊", "携带", "生育"], quizAnswer: 0,
            quizExplanation: "bear the pain = 忍受疼痛，是动词僻义；'熊'是名词常见义，与 could hardly(几乎不能)的语境和词性都不符。"),
        VocabWord(id: "v_second", headword: "second", meaning: "常义:第二/秒；僻义:vt. 赞同", tier: 2, category: .polysemy,
            example: "I'd like to second the proposal made by my colleague.",
            exampleMeaning: "我想对我同事提出的建议表示赞同。",
            collocations: ["second a proposal/motion"],
            quizStem: "I'd like to second the proposal made by my colleague. \"Second\" here means ___.",
            quizOptions: ["赞同", "排第二", "秒", "派往(借调)"], quizAnswer: 0,
            quizExplanation: "second the proposal = 赞同提议，是动词僻义，常用于正式会议场景；'第二/秒'是常见义，与本句动词位置不符。"),
        VocabWord(id: "v_mean", headword: "mean", meaning: "常义:v. 意思是；僻义:adj. 吝啬的，卑鄙的", tier: 1, category: .polysemy,
            example: "He was too mean to even buy his friends a cup of coffee.",
            exampleMeaning: "他太吝啬了，甚至不愿意给朋友买一杯咖啡。",
            collocations: ["too mean to do sth"],
            quizStem: "He was too mean to even buy his friends a cup of coffee. \"Mean\" here means ___.",
            quizOptions: ["吝啬的", "意思是", "平均的", "中等的"], quizAnswer: 0,
            quizExplanation: "too mean to do = 太吝啬而不愿做，是形容词僻义；'意思是'是动词常见义，词性不符。"),
        VocabWord(id: "v_present", headword: "present", meaning: "常义:n. 礼物；僻义:adj. 出席的", tier: 1, category: .polysemy,
            example: "All the club members were present at yesterday's meeting.",
            exampleMeaning: "俱乐部所有成员都出席了昨天的会议。",
            collocations: ["be present at"],
            quizStem: "All the club members were present at yesterday's meeting. \"Present\" here means ___.",
            quizOptions: ["出席的", "礼物", "现在的", "赠送"], quizAnswer: 0,
            quizExplanation: "be present at = 出席，是形容词僻义；'礼物'是名词常见义，与 were(系动词)+___+at 的结构不符。"),
    ]

    // MARK: 二期扩充·搭配辨析(10 → 20 词)

    static let collocationWords2: [VocabWord] = [
        VocabWord(id: "v_lay", headword: "lay", meaning: "vt. 放置，摆放(及物，三态 lay-laid-laid)", tier: 1, category: .collocation,
            example: "She carefully laid the baby down in the crib without making a sound.",
            exampleMeaning: "她小心地把婴儿放进婴儿床，没有发出一点声音。",
            collocations: ["lay the table", "lay sth down"],
            quizStem: "She carefully ___ the baby down in the crib without making a sound.",
            quizOptions: ["laid", "lay", "lied", "lain"], quizAnswer: 0,
            quizExplanation: "lay(放置)的过去式是laid，及物动词需带宾语baby；lie(躺/位于)是不及物动词，lied是lie(撒谎)的过去式，意思不符。"),
        VocabWord(id: "v_lie", headword: "lie", meaning: "vi. 躺；位于(不及物，三态 lie-lay-lain)", tier: 1, category: .collocation,
            example: "The old village lies quietly at the foot of the mountain.",
            exampleMeaning: "这个古老的村庄静静地坐落在山脚下。",
            collocations: ["lie at the foot of", "lie in bed"],
            quizStem: "The old village ___ quietly at the foot of the mountain.",
            quizOptions: ["lies", "lays", "lied", "laid"], quizAnswer: 0,
            quizExplanation: "lie(位于)是不及物动词，第三人称单数是lies；lay(放置)是及物动词，此处没有宾语，不能用lay。"),
        VocabWord(id: "v_bring", headword: "bring", meaning: "vt. 带来(朝说话人方向)", tier: 1, category: .collocation,
            example: "Please remember to bring your textbook to class tomorrow.",
            exampleMeaning: "请记得明天把课本带来上课。",
            collocations: ["bring sth to sb", "bring about"],
            quizStem: "Please remember to ___ your textbook to class tomorrow.",
            quizOptions: ["bring", "take", "carry", "fetch"], quizAnswer: 0,
            quizExplanation: "bring 指带向说话人所在的地方；take 指带离说话人所在地，方向相反。"),
        VocabWord(id: "v_take", headword: "take", meaning: "vt. 带走(离开说话人方向)", tier: 1, category: .collocation,
            example: "Don't forget to take your umbrella with you when you leave.",
            exampleMeaning: "你离开的时候别忘了带上雨伞。",
            collocations: ["take sth with you", "take away"],
            quizStem: "Don't forget to ___ your umbrella with you when you leave.",
            quizOptions: ["take", "bring", "carry", "fetch"], quizAnswer: 0,
            quizExplanation: "take 指带离当前地点；bring 指带向说话人所在地，方向相反，此处主语正在离开，应用take。"),
        VocabWord(id: "v_sensible", headword: "sensible", meaning: "adj. 明智的，合理的", tier: 1, category: .collocation,
            example: "It would be sensible to leave early to avoid the traffic jam.",
            exampleMeaning: "提前出发以避开交通堵塞是明智的。",
            collocations: ["a sensible decision", "sensible advice"],
            quizStem: "It would be ___ to leave early to avoid the traffic jam.",
            quizOptions: ["sensible", "sensitive", "sensational", "senseless"], quizAnswer: 0,
            quizExplanation: "sensible 指明智的、合理的；sensitive 指敏感的，与避开堵塞的理性建议语境不符。"),
        VocabWord(id: "v_sensitive", headword: "sensitive", meaning: "adj. 敏感的", tier: 1, category: .collocation,
            example: "Many teenagers are quite sensitive about their appearance.",
            exampleMeaning: "许多青少年对自己的外表相当敏感。",
            collocations: ["sensitive to", "a sensitive topic"],
            quizStem: "Many teenagers are quite ___ about their appearance.",
            quizOptions: ["sensitive", "sensible", "sensational", "senseless"], quizAnswer: 0,
            quizExplanation: "sensitive 指敏感的，常与about搭配；sensible 指明智的，与在意外表的情绪语境不符。"),
        VocabWord(id: "v_successful", headword: "successful", meaning: "adj. 成功的", tier: 2, category: .collocation,
            example: "The fundraising event turned out to be highly successful.",
            exampleMeaning: "这次筹款活动结果非常成功。",
            collocations: ["a successful attempt", "successful in doing sth"],
            quizStem: "The fundraising event turned out to be highly ___.",
            quizOptions: ["successful", "successive", "success", "succeed"], quizAnswer: 0,
            quizExplanation: "successful 是形容词成功的；successive 指连续的，词义不符；success/succeed 词性不对，不能作be后的补语形容词。"),
        VocabWord(id: "v_successive", headword: "successive", meaning: "adj. 连续的，依次的", tier: 2, category: .collocation,
            example: "The team has won the championship for three successive years.",
            exampleMeaning: "这个队连续三年赢得了冠军。",
            collocations: ["successive years", "on successive days"],
            quizStem: "The team has won the championship for three ___ years.",
            quizOptions: ["successive", "successful", "success", "succeeding"], quizAnswer: 0,
            quizExplanation: "successive 指连续的，强调一年接一年；本句考查的搭配点是'连续三年'而非'成功的'，故选successive。"),
        VocabWord(id: "v_historic", headword: "historic", meaning: "adj. 有历史意义的，重大的", tier: 2, category: .collocation,
            example: "Landing on the moon was a historic moment for all of humankind.",
            exampleMeaning: "登上月球对全人类来说是一个具有历史意义的时刻。",
            collocations: ["a historic moment", "historic site"],
            quizStem: "Landing on the moon was a ___ moment for all of humankind.",
            quizOptions: ["historic", "historical", "history", "historian"], quizAnswer: 0,
            quizExplanation: "historic 指具有重大历史意义的；historical 指历史上的、与历史有关的，语义偏中性，与本句'重大意义'不符。"),
        VocabWord(id: "v_historical", headword: "historical", meaning: "adj. 历史的，与历史相关的", tier: 2, category: .collocation,
            example: "The museum displays a collection of historical documents from the last century.",
            exampleMeaning: "博物馆展出了上世纪的一批历史文件。",
            collocations: ["historical documents", "historical research"],
            quizStem: "The museum displays a collection of ___ documents from the last century.",
            quizOptions: ["historical", "historic", "history", "historian"], quizAnswer: 0,
            quizExplanation: "historical 指与历史相关的，修饰documents恰当；historic 强调具有重大意义的，语义过重，不适合泛指的文件。"),
        VocabWord(id: "v_considerate", headword: "considerate", meaning: "adj. 体贴的，考虑周到的(指人)", tier: 2, category: .collocation,
            example: "It was very considerate of you to remember my birthday.",
            exampleMeaning: "你能记得我的生日真是太体贴了。",
            collocations: ["considerate of sb to do sth"],
            quizStem: "It was very ___ of you to remember my birthday.",
            quizOptions: ["considerate", "considerable", "considering", "consideration"], quizAnswer: 0,
            quizExplanation: "considerate 指体贴的，常用 it's considerate of sb to do 句型；considerable 指相当大的，修饰程度而非人的品质。"),
        VocabWord(id: "v_considerable", headword: "considerable", meaning: "adj. 相当大的，可观的", tier: 2, category: .collocation,
            example: "Repairing the old bridge will require a considerable amount of money.",
            exampleMeaning: "修复这座老桥需要相当大的一笔资金。",
            collocations: ["a considerable amount of", "considerable effort"],
            quizStem: "Repairing the old bridge will require a ___ amount of money.",
            quizOptions: ["considerable", "considerate", "considering", "consideration"], quizAnswer: 0,
            quizExplanation: "considerable 指相当大的，修饰amount；considerate 指人体贴的，不能修饰money的数量。"),
        VocabWord(id: "v_principal", headword: "principal", meaning: "n. 校长；adj. 主要的", tier: 1, category: .collocation,
            example: "The principal announced the new school rules at this morning's assembly.",
            exampleMeaning: "校长在今天早上的全校集会上宣布了新的校规。",
            collocations: ["the school principal", "the principal reason"],
            quizStem: "The ___ announced the new school rules at this morning's assembly.",
            quizOptions: ["principal", "principle", "principled", "principally"], quizAnswer: 0,
            quizExplanation: "principal 作名词指校长；principle 指原则，词义不符，且本句需要一个表示人的名词。"),
        VocabWord(id: "v_principle", headword: "principle", meaning: "n. 原则", tier: 1, category: .collocation,
            example: "Honesty is one of the most important principles in her life.",
            exampleMeaning: "诚实是她生活中最重要的原则之一。",
            collocations: ["in principle", "a basic principle"],
            quizStem: "Honesty is one of the most important ___ in her life.",
            quizOptions: ["principles", "principals", "principal", "principle"], quizAnswer: 0,
            quizExplanation: "principle 指抽象的原则，此处需复数形式principles；principal 指校长或主要的，与语境不符。"),
        VocabWord(id: "v_complement", headword: "complement", meaning: "vt./n. 补充，使更完美", tier: 2, category: .collocation,
            example: "The soft music perfectly complemented the calm atmosphere of the restaurant.",
            exampleMeaning: "柔和的音乐完美地衬托了餐厅平静的氛围。",
            collocations: ["complement each other", "a perfect complement to"],
            quizStem: "The soft music perfectly ___ the calm atmosphere of the restaurant.",
            quizOptions: ["complemented", "complimented", "completed", "compelled"], quizAnswer: 0,
            quizExplanation: "complement 指补充、衬托，使更完美；compliment 指赞美，发音相同但意思不同，是典型的同音混淆词。"),
        VocabWord(id: "v_compliment", headword: "compliment", meaning: "n./vt. 赞美，称赞", tier: 2, category: .collocation,
            example: "She blushed when he complimented her on her excellent presentation.",
            exampleMeaning: "他称赞她出色的演讲时，她脸红了。",
            collocations: ["compliment sb on sth", "pay sb a compliment"],
            quizStem: "She blushed when he ___ her on her excellent presentation.",
            quizOptions: ["complimented", "complemented", "completed", "compelled"], quizAnswer: 0,
            quizExplanation: "compliment sb on sth 指就某事称赞某人；complement 指补充/衬托，与称赞演讲的语境不符，是同音混淆陷阱。"),
        VocabWord(id: "v_lose", headword: "lose", meaning: "vt. 丢失，输掉", tier: 1, category: .collocation,
            example: "If you don't back up your files, you might lose all your work.",
            exampleMeaning: "如果你不备份文件，可能会丢失所有的工作成果。",
            collocations: ["lose one's way", "lose weight"],
            quizStem: "If you don't back up your files, you might ___ all your work.",
            quizOptions: ["lose", "loose", "loss", "lost"], quizAnswer: 0,
            quizExplanation: "lose 是动词丢失；loose 是形容词松的，词性不符，不能直接跟宾语work。"),
        VocabWord(id: "v_loose", headword: "loose", meaning: "adj. 松的，宽松的", tier: 1, category: .collocation,
            example: "These trousers are too loose around the waist; I need a smaller size.",
            exampleMeaning: "这条裤子腰部太松了，我需要小一号的。",
            collocations: ["a loose fit", "come loose"],
            quizStem: "These trousers are too ___ around the waist; I need a smaller size.",
            quizOptions: ["loose", "lose", "loss", "lost"], quizAnswer: 0,
            quizExplanation: "loose 是形容词松的，修饰trousers合适；lose 是动词丢失，词性和语义都不符。"),
        VocabWord(id: "v_adapt", headword: "adapt", meaning: "vi./vt. 适应；改编", tier: 1, category: .collocation,
            example: "It took her a while to adapt to the fast pace of city life.",
            exampleMeaning: "她花了一段时间才适应了城市生活的快节奏。",
            collocations: ["adapt to", "adapt a novel for the screen"],
            quizStem: "It took her a while to ___ to the fast pace of city life.",
            quizOptions: ["adapt", "adopt", "adept", "adopted"], quizAnswer: 0,
            quizExplanation: "adapt to 指适应，固定搭配；adopt 指采纳/收养，与适应城市生活节奏的语境不符。"),
        VocabWord(id: "v_adopt", headword: "adopt", meaning: "vt. 采纳，采用；收养", tier: 1, category: .collocation,
            example: "The school decided to adopt a new method of teaching grammar.",
            exampleMeaning: "学校决定采用一种新的语法教学方法。",
            collocations: ["adopt a policy", "adopt a child"],
            quizStem: "The school decided to ___ a new method of teaching grammar.",
            quizOptions: ["adopt", "adapt", "adept", "adapted"], quizAnswer: 0,
            quizExplanation: "adopt 指采纳、采用(新方法/政策)；adapt 指使适应，常与to搭配，此处语境是采用新方法，应选adopt。"),
    ]

    // MARK: 二期扩充·熟词僻义(10 → 25 词)

    static let polysemyWords2: [VocabWord] = [
        VocabWord(id: "v_match", headword: "match", meaning: "常义:n. 比赛；僻义:vt. 与……相配/匹敌", tier: 1, category: .polysemy,
            example: "No one in the class could match her speed in the 100-meter race.",
            exampleMeaning: "班里没有人能在100米赛跑中比得上她的速度。",
            collocations: ["match sb in sth", "a perfect match"],
            quizStem: "No one in the class could match her speed in the 100-meter race. \"Match\" here means ___.",
            quizOptions: ["比得上", "比赛", "火柴", "配对"], quizAnswer: 0,
            quizExplanation: "match sb in sth = 在某方面比得上某人，是动词僻义；'比赛/火柴'是名词常见义，与此处的动词位置不符。"),
        VocabWord(id: "v_company", headword: "company", meaning: "常义:n. 公司；僻义:n. 陪伴，相伴", tier: 1, category: .polysemy,
            example: "After his wife passed away, the old man's dog became his only company.",
            exampleMeaning: "妻子去世后，那只狗成了老人唯一的陪伴。",
            collocations: ["keep sb company", "in the company of"],
            quizStem: "After his wife passed away, the old man's dog became his only company. \"Company\" here means ___.",
            quizOptions: ["陪伴", "公司", "一群人", "连队"], quizAnswer: 0,
            quizExplanation: "company 在此指陪伴，是名词僻义；'公司'是更常见义，与'狗成了他唯一的……'的语境不符。"),
        VocabWord(id: "v_capital", headword: "capital", meaning: "常义:n. 首都；僻义:n. 资金/大写字母", tier: 2, category: .polysemy,
            example: "The young entrepreneur struggled to raise enough capital to launch her startup.",
            exampleMeaning: "这位年轻的企业家很难筹集到足够的资金来启动她的创业公司。",
            collocations: ["raise capital", "capital letter"],
            quizStem: "The young entrepreneur struggled to raise enough capital to launch her startup. \"Capital\" here means ___.",
            quizOptions: ["资金", "首都", "大写字母", "死刑"], quizAnswer: 0,
            quizExplanation: "raise capital = 筹集资金，是名词僻义；'首都'是常见义，与'创业筹钱'的商业语境不符。"),
        VocabWord(id: "v_interest", headword: "interest", meaning: "常义:n. 兴趣；僻义:n. 利息", tier: 1, category: .polysemy,
            example: "If you don't pay off your credit card bill, the bank will charge you interest.",
            exampleMeaning: "如果你不还清信用卡账单，银行会向你收取利息。",
            collocations: ["pay interest", "charge interest"],
            quizStem: "If you don't pay off your credit card bill, the bank will charge you interest. \"Interest\" here means ___.",
            quizOptions: ["利息", "兴趣", "利益", "关注"], quizAnswer: 0,
            quizExplanation: "charge interest = 收取利息，是金融领域的名词僻义；'兴趣'是常见义，与'信用卡账单'的语境不符。"),
        VocabWord(id: "v_fine", headword: "fine", meaning: "常义:adj. 好的/晴朗的；僻义:n./vt. 罚款", tier: 1, category: .polysemy,
            example: "Drivers who park illegally on this street will be fined fifty dollars.",
            exampleMeaning: "在这条街上违规停车的司机将被罚款五十美元。",
            collocations: ["fine sb for sth", "pay a fine"],
            quizStem: "Drivers who park illegally on this street will be fined fifty dollars. \"Fined\" here means ___.",
            quizOptions: ["罚款", "美好的", "晴朗的", "精细的"], quizAnswer: 0,
            quizExplanation: "be fined = 被罚款，是动词僻义；'美好的/晴朗的'是形容词常见义，与被动语态的结构不符。"),
        VocabWord(id: "v_count", headword: "count", meaning: "常义:v. 数数；僻义:v. 重要；count on 依靠", tier: 1, category: .polysemy,
            example: "In an emergency like this, every single second counts.",
            exampleMeaning: "在这样的紧急情况下，每一秒钟都很重要。",
            collocations: ["count on sb", "every second counts"],
            quizStem: "In an emergency like this, every single second counts. \"Counts\" here means ___.",
            quizOptions: ["很重要", "数数", "计算", "包括"], quizAnswer: 0,
            quizExplanation: "count 在此指重要、有价值，是动词僻义；'数数'是常见义，与'每一秒钟都……'强调重要性的语境不符。"),
        VocabWord(id: "v_note", headword: "note", meaning: "常义:n. 笔记；僻义:vt. 注意到/n. 纸币", tier: 1, category: .polysemy,
            example: "Please note that the museum will be closed for renovation next month.",
            exampleMeaning: "请注意，博物馆下个月将因装修而关闭。",
            collocations: ["note that...", "take note of"],
            quizStem: "Please note that the museum will be closed for renovation next month. \"Note\" here means ___.",
            quizOptions: ["注意", "做笔记", "纸币", "音符"], quizAnswer: 0,
            quizExplanation: "note that... = 注意到……，是动词僻义；'做笔记/纸币'都是名词常见义，与此处的动词位置不符。"),
        VocabWord(id: "v_plant", headword: "plant", meaning: "常义:n. 植物；僻义:n. 工厂/vt. 种植，安置", tier: 2, category: .polysemy,
            example: "The new car plant is expected to create thousands of jobs in the region.",
            exampleMeaning: "这家新汽车工厂预计将为该地区创造数千个就业机会。",
            collocations: ["a power plant", "plant trees"],
            quizStem: "The new car plant is expected to create thousands of jobs in the region. \"Plant\" here means ___.",
            quizOptions: ["工厂", "植物", "种植", "安置"], quizAnswer: 0,
            quizExplanation: "car plant = 汽车工厂，是名词僻义；'植物'是常见义，与'创造就业机会'的工业语境不符。"),
        VocabWord(id: "v_spring", headword: "spring", meaning: "常义:n. 春天；僻义:n. 泉水/vi. 弹起", tier: 2, category: .polysemy,
            example: "A small spring near the village provides clean water for the local farmers.",
            exampleMeaning: "村子附近的一条小泉为当地农民提供了干净的水源。",
            collocations: ["a hot spring", "spring up"],
            quizStem: "A small spring near the village provides clean water for the local farmers. \"Spring\" here means ___.",
            quizOptions: ["泉水", "春天", "弹簧", "跳跃"], quizAnswer: 0,
            quizExplanation: "spring 在此指泉水，是名词僻义；'春天'是常见义，与'提供干净水源'的语境不符。"),
        VocabWord(id: "v_board", headword: "board", meaning: "常义:n. 木板；僻义:n. 董事会/vt. 登(机、船、车)", tier: 2, category: .polysemy,
            example: "Passengers are kindly requested to board the aircraft through gate twelve.",
            exampleMeaning: "请乘客从十二号登机口登机。",
            collocations: ["board a plane", "room and board"],
            quizStem: "Passengers are kindly requested to board the aircraft through gate twelve. \"Board\" here means ___.",
            quizOptions: ["登上", "木板", "董事会", "包伙食"], quizAnswer: 0,
            quizExplanation: "board the aircraft = 登机，是动词僻义；'木板'是常见义，与'乘客通过登机口……飞机'的语境不符。"),
        VocabWord(id: "v_observe", headword: "observe", meaning: "常义:v. 观察；僻义:v. 遵守/评论说", tier: 2, category: .polysemy,
            example: "All visitors to the temple are expected to observe the local customs.",
            exampleMeaning: "所有参观寺庙的游客都应该遵守当地的习俗。",
            collocations: ["observe the rules", "observe that..."],
            quizStem: "All visitors to the temple are expected to observe the local customs. \"Observe\" here means ___.",
            quizOptions: ["遵守", "观察", "注意到", "庆祝"], quizAnswer: 0,
            quizExplanation: "observe the customs = 遵守习俗，是动词僻义；'观察'是常见义，与'游客应该……当地习俗'的规则语境不符。"),
        VocabWord(id: "v_appreciate", headword: "appreciate", meaning: "常义:v. 欣赏；僻义:v. 感激/意识到", tier: 1, category: .polysemy,
            example: "I would really appreciate it if you could reply to my email as soon as possible.",
            exampleMeaning: "如果你能尽快回复我的邮件，我会非常感激。",
            collocations: ["appreciate it if...", "fully appreciate"],
            quizStem: "I would really appreciate it if you could reply to my email as soon as possible. \"Appreciate\" here means ___.",
            quizOptions: ["感激", "欣赏", "增值", "理解"], quizAnswer: 0,
            quizExplanation: "would appreciate it if... = 如果……我会很感激，是礼貌句式中的僻义；'欣赏'(艺术/风景)是常见义，与请求语境不符。"),
        VocabWord(id: "v_entertain", headword: "entertain", meaning: "常义:v. 使娱乐；僻义:v. 招待/考虑(想法)", tier: 2, category: .polysemy,
            example: "The couple loves to entertain friends and family at their home every weekend.",
            exampleMeaning: "这对夫妇每个周末都喜欢在家里招待朋友和家人。",
            collocations: ["entertain guests", "entertain an idea"],
            quizStem: "The couple loves to entertain friends and family at their home every weekend. \"Entertain\" here means ___.",
            quizOptions: ["招待", "使娱乐", "考虑", "包含"], quizAnswer: 0,
            quizExplanation: "entertain friends and family = 招待朋友和家人，是动词僻义；'使娱乐'是常见义，待客语境下'招待'更准确。"),
        VocabWord(id: "v_exercise", headword: "exercise", meaning: "常义:n./v. 锻炼；僻义:vt. 运用，行使", tier: 1, category: .polysemy,
            example: "The judge urged the jury to exercise great caution before reaching a verdict.",
            exampleMeaning: "法官敦促陪审团在做出判决前要运用极大的谨慎。",
            collocations: ["exercise caution", "exercise power"],
            quizStem: "The judge urged the jury to exercise great caution before reaching a verdict. \"Exercise\" here means ___.",
            quizOptions: ["运用", "锻炼", "练习", "行使"], quizAnswer: 0,
            quizExplanation: "exercise caution = 保持/运用谨慎，是动词僻义；'锻炼身体'是常见义，与'陪审团做判决前……谨慎'的语境不符。"),
        VocabWord(id: "v_fair", headword: "fair", meaning: "常义:adj. 公平的；僻义:n. 集市，游乐场", tier: 1, category: .polysemy,
            example: "Hundreds of visitors flocked to the annual summer fair held in the town square.",
            exampleMeaning: "数百名游客涌向在镇广场举行的年度夏季集市。",
            collocations: ["a funfair", "a fair amount of"],
            quizStem: "Hundreds of visitors flocked to the annual summer fair held in the town square. \"Fair\" here means ___.",
            quizOptions: ["集市", "公平的", "金发的", "中等的"], quizAnswer: 0,
            quizExplanation: "summer fair = 夏季集市/游园会，是名词僻义；'公平的'是常见形容词义，此处fair是被held修饰的名词，词性不符。"),
    ]
}
